AWSTemplateFormatVersion: 2010-09-09
Description: "This creates a EC2 with the availability to choose from priv to pub subnet"
Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !FindInMap [SubnetMap, "AWS::Region", !Ref SubnetType]
      ImageId: !FindInMap [SubnetMap, "AWS::Region", LinuxImg]
      ImageId: !FindInMap [ImageMap, ImageType, !Ref ImageVersion]
      #KeyName: virginia-kp
      ImageId: ami-0323c3dd2da7fb37d
      InstanceType: t2.micro
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install httpd -y
        service httpd start 
        chkconfig httpd on 
        cd /var/www/html
        echo "<html><h1>This is Martin's SERVER</h1><p>Awesome I'm learning so much from MyDevOps Academy</p></html>" > index.html
      Tags:
        - Key: Name
          Value: EC2-test 

#Parameter to be able to choose from priv to pub sub
Parameters:
  ImageVersion:
    Description: Choose Windows or Linux
    Type: String
    Default: Windows
    AllowedValues:
      - Windows
      - Linux
  InstanceType:
    Description: Enter t2.nano, t2.micro, t2.small. Default is t2.nano
    Type: String
    Default: medium
    AllowedValues:
      - small
      - medium 
      - large 
  SubnetType:
    Description: Choose SubnetType
    Type: String
    Default: PublicSubnet
    AllowedValues:
      - PublicSubnet
      - PrivateSubnet
 
#Mapping for parameter
Mappings:
  SubnetMap:
    us-east-1:
      PublicSubnet: subnet-0aa237ea1e99c1108
      PrivateSubnet: subnet-0aee0e6759a2286eb
  InstanceMap:
    us-east-1:
      small: t2.nano
      medium: t2.micro
      large: t2.small
  ImageType:
      Windows: ami-0c278895328cddfdd
      Linux: ami-06fcc1f0bc2c8943f








      


  
      
