AWSTemplateFormatVersion: 2010-09-09
Parameters: 
  BucketName:
    Description: Unique name for your bucket. This will be in the S3 url to your React app.
    Type: String
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead 
      WebsiteConfiguration: 
        IndexDocument: index.html 
        ErrorDocument: index.html 
  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyBucket 
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement: 
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*' 
            Action: 's3:GetObject'
            Resource: !Join ['', ['arn:aws:s3:::', !Ref MyBucket, /*]]
Outputs:
  WebsiteURL:
    Value: !GetAtt MyBucket.WebsiteURL
    Description: "Public S3Bucket"