AWSTemplateFormatVersion: 2010-09-09
Description: "This creates a vpc w 2 pubsub n 2 privsub"
Resources: 
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: vpc-4sub, 2priv 2publ
          
  #1 Subs
  PrivateSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
       - 0
       - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.1/24
      Tags:
        - Key: Name
          Value: PrivateSubnet01
  PublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
       - 0
       - Fn::GetAZs: !Ref 'AWS::Region'    
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.2/24
      Tags:
        - Key: Name
          Value: PublicSubnet01

  #2 Subs
  PrivateSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
       - 1
       - Fn::GetAZs: !Ref 'AWS::Region'
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.3/24
      Tags:
        - Key: Name
          Value: PrivateSubnet02
  PublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
       - 1
       - Fn::GetAZs: !Ref 'AWS::Region'    
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.4/24
      Tags:
        - Key: Name
          Value: PublicSubnet02

  #Custom RT
  CustomRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: CustomRT
  #Internet Gateway
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: IGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref IGW

  #Route to IGW
  routeName:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref CustomRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  #Route from Pubsub to CustomRT
  routeTableAssocName:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        - !Ref PublicSubnet01
      RouteTableId: !Ref CustomRT
  
  routeTableAssocName:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: 
        - !Ref PublicSubnet02
      RouteTableId: !Ref CustomRT