AWSTemplateFormatVersion: 2010-09-09
Description: "This template creates vpc with 2 subnets. 1 private, 1 public"
  
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Virginia-Finance-app
  #Private Subnet 1       
  PrivateSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        !Select
        - 0
        - Fn::GetAZs: ''
      VpcId: !Ref myVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: Private Subnet-A   
  #Private Subnet   2     
  PrivateSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        !Select
        - 1
        - Fn::GetAZs: ''
      VpcId: !Ref myVPC
      CidrBlock: 10.0.2.0/24
      Tags:
        - Key: Name
          Value: Private Subnet-B 
  #Public Subnet 1
  PublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        !Select
        - 1
        - Fn::GetAZs: ''
      VpcId: !Ref myVPC
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: Public Subnet-A    
  #Public Subnet 2
  PublicSubnet02:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        !Select
        - 0
        - Fn::GetAZs: ''
      VpcId: !Ref myVPC
      CidrBlock: 10.0.4.0/24
      Tags:
        - Key: Name
          Value: Public Subnet-B  
  # Custom RT
  CustomRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: CustomRT-finance-app     
  FinanceIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: FinanceIGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref FinanceIGW
  RouteToIGW:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref CustomRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FinanceIGW
  
  routeTableAssocName01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet01 
      RouteTableId: !Ref CustomRT
  routeTableAssocName02:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet02
      RouteTableId: !Ref CustomRT